amadeus4dev/developer-guides

guides/authorization.md

@alnacle can you review and merge please?

Updates to the authorization guide

---

docs/resources/hotels.md

update hotel tutorials 
+ updated based on Hotel Search V3 
+ migrated a blog about multiple hotel rooms (https://developers.amadeus.com/blog/how-to-book-multiple-rooms-amadeus-hotel-booking-api) 
+ updated the structures 
to add further in next iteration  : 
1. Autocomplete Hotel Names
2. Notes about commissions

update hotel tutorials

---

.github/workflows/mkdocs.yml
mkdocs.yml

add 2 social media and google analytics

add 2 social media and google analytics

---

docs/resources/market-insight.md
mkdocs.yml

update market insight
remove the old categories

update market insight

---

mkdocs.yml
requirements.txt

updated mkdocs-materials to the latest 
added google analytics and helpful feedback

google analytics and feedback

---

docs/examples/code-example.md

- Covid-19 and travel safety
- Hotel 
- change the order to follow the portal order categories

Add pending examples

---

docs/test-data.md

update data collection missing APIs

---

docs/glossary.md
docs/resources/flights.md
overrides/main.html

- Removed banner 
- corrected https://www.iata.org in glossary.md
- added {:target="\_blank"} in glossary.md 
- corrected a redirection in flights.md

Remove banner

---

docs/examples/prototypes.md

Hotel List added in prototype page

Hotel List update in prototypes

---

docs/test-data.md

This PR adds more information to the data collection page: 
- Extended first paragraph
- Added warning for it's use 
- Test vs Prod table
- Link to rate limits and pricing 
- How to check how much quota used
Let me know if there is anything else that could be added to make the page more interesting.

Update data collection

---

docs/resources/flights.md
docs/resources/hotels.md

- Respective links to interactive code examples added to `hotel` and `flight` tutorials

add links to interactive examples from tutorials

---

overrides/main.html

Remove all references of an old banner that still shows up

Fix banner removal

---

.github/contributing.md

- Fixed Discord link
- Added links to open in a new tab
- Updated a sentence that I struggled a bit to understand while reading

Fixed Discord link

---

docs/developer-tools/index.md

- Added links to get started repos on SDKs at the SDKs table
- Simplified the table

Add links to get started repos on SDKs

---

docs/test-data.md

Update test data collection categories

---

overrides/main.html

Reverts amadeus4dev/developer-guides#175

Revert "Redirectiontest"

---

overrides/main.html

Reverts amadeus4dev/developer-guides#184

Revert "apply the each page udpate"

---

overrides/main.html

Reverts amadeus4dev/developer-guides#183

Revert "remove /"

---

docs/examples/prototypes.md

- Added source code links together with the demo links 
- Updated anchor names for more user-friendliness.

Update code links for official prototypes

---

mkdocs.yml

change base url for canonical changes

change base url

---

overrides/main.html

Reverts amadeus4dev/developer-guides#207

Revert "Test to see if URL to main portal works"

---

docs/resources/hotels.md

Add pricing info for multiple rooms

---

docs/faq.md
docs/resources/flights.md

Add restrictions for Delta
